### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by rugk** [ENT8R/CompleteStreetComplete#1]
A click on "Download data" leads to a 404 error.

**Comment by ENT8R** [comment]
But if you go to https://ent8r.lima-city.de/CompleteStreetComplete/api/get you can see the data?
And what happens if you go to https://ent8r.lima-city.de/CompleteStreetComplete/api/data.json ?

**Comment by ENT8R** [comment]
Oops, you were right! I found the mistake... It was just a wrong url...
